"""Render a validated harness into files and apply/revert it in a workspace.

AGENTS.md keeps its original content; the harness lives in one marked block
that is replaced on re-apply and removed on revert. Area guides are written to
.harness/skills/<area>/SKILL.md and referenced from that block, because a file
in .harness/ is not loaded by any agent on its own.
"""

import hashlib
import json
import shutil
from pathlib import Path

BEGIN = "<!-- AUTOHARNESS:BEGIN -->"
END = "<!-- AUTOHARNESS:END -->"
TOKEN_BUDGET = 3000  # common block + one area guide, estimated
AREA_TITLES = {"backend": "Backend", "frontend": "Frontend", "testing": "Testing", "data": "Data"}


def estimate_tokens(text):
    # Conservative (code and Markdown average ~3.5-4 characters per token).
    return -(-len(text) // 3)


def _sources(paths):
    return ", ".join(f"`{p}`" for p in paths)


def render(project, harness, generator):
    areas = sorted({item["area"] for section in ("rules", "workflows", "pitfalls") for item in harness[section]}
                   - {"general"})
    lines = [BEGIN, "## Project guide (generated from repository evidence)", "", harness["summary"].strip(), "",
             "### Rules for every change"]
    general = [r for r in harness["rules"] if r["area"] == "general"]
    lines += [f"- {r['rule'].strip()} (source: {_sources(r['evidence_paths'])})" for r in general] or ["- See the area guides."]
    if harness["commands"]:
        lines += ["", "### Commands"]
        lines += [f"- {c['purpose']}: `{c['command']}`" for c in harness["commands"]]
    if areas:
        lines += ["", "### Area guides", "Before changing code in an area, read its guide:"]
        lines += [f"- {AREA_TITLES[a].lower()}: `.harness/skills/{a}/SKILL.md`" for a in areas]
    lines += [END]
    block = "\n".join(lines) + "\n"

    skills = {}
    for area in areas:
        title = AREA_TITLES[area]
        body = ["---", f"name: {project['name']}-{area}",
                f"description: {title} conventions for this repository. Read before changing {area} code.", "---",
                f"# {title} guide", ""]
        rules = [r for r in harness["rules"] if r["area"] == area]
        if rules:
            body += ["## Rules"] + [f"- {r['rule'].strip()} (source: {_sources(r['evidence_paths'])})" for r in rules] + [""]
        for wf in (w for w in harness["workflows"] if w["area"] == area):
            if wf["steps"]:
                body += ["## Steps"] + [f"{i}. {s.strip()}" for i, s in enumerate(wf["steps"], 1)] + [""]
            if wf["checks"]:
                body += ["## Before finishing"] + [f"- {c.strip()}" for c in wf["checks"]] + [""]
        pitfalls = [p for p in harness["pitfalls"] if p["area"] == area]
        if pitfalls:
            body += ["## Pitfalls"] + [f"- {p['text'].strip()} (source: {_sources(p['evidence_paths'])})" for p in pitfalls] + [""]
        body += ["## Provenance", f"Generated by {generator} from commit `{project['commit']}`."]
        skills[area] = "\n".join(body) + "\n"

    sizes = {"agents_block": estimate_tokens(block), **{a: estimate_tokens(t) for a, t in skills.items()}}
    largest = max((v for k, v in sizes.items() if k != "agents_block"), default=0)
    budget = {"estimated_tokens": sizes, "worst_case_loaded": sizes["agents_block"] + largest,
              "limit": TOKEN_BUDGET, "within_limit": sizes["agents_block"] + largest <= TOKEN_BUDGET,
              "method": "ceil(chars / 3), not a real tokenizer"}
    return {"agents_block": block, "skills": skills, "budget": budget}


def _strip_block(text):
    if BEGIN not in text:
        return text
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return (head.rstrip("\n") + "\n" + tail.lstrip("\n")).rstrip("\n") + "\n" if head.strip() else tail.lstrip("\n")


def apply(rendered, workspace, manifest):
    workspace = Path(workspace)
    agents = workspace / "AGENTS.md"
    harness_dir = workspace / ".harness"
    backup = harness_dir / "AGENTS.md.orig"
    if harness_dir.exists() and not backup.exists() and not (harness_dir / "AGENTS.absent").exists():
        raise SystemExit(f"{harness_dir} exists but was not created by this tool; refusing to overwrite")
    original = None
    if backup.exists():
        original = backup.read_text(encoding="utf-8")
    elif agents.exists():
        original = _strip_block(agents.read_text(encoding="utf-8"))
    if harness_dir.exists():
        shutil.rmtree(harness_dir)
    (harness_dir / "skills").mkdir(parents=True)
    if original is None:
        (harness_dir / "AGENTS.absent").write_text("", encoding="utf-8")
        agents.write_text(rendered["agents_block"], encoding="utf-8")
    else:
        backup.write_text(original, encoding="utf-8")
        agents.write_text(original.rstrip("\n") + "\n\n" + rendered["agents_block"], encoding="utf-8")
    for area, text in rendered["skills"].items():
        (harness_dir / "skills" / area).mkdir()
        (harness_dir / "skills" / area / "SKILL.md").write_text(text, encoding="utf-8")
    files = {p.relative_to(workspace).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
             for p in sorted([agents, *harness_dir.rglob("SKILL.md")])}
    (harness_dir / "manifest.json").write_text(json.dumps(dict(manifest, files=files), indent=2) + "\n", encoding="utf-8")
    return files


def revert(workspace):
    workspace = Path(workspace)
    harness_dir = workspace / ".harness"
    agents = workspace / "AGENTS.md"
    if not harness_dir.exists():
        return False
    if (harness_dir / "AGENTS.absent").exists():
        agents.unlink(missing_ok=True)
    else:
        agents.write_text((harness_dir / "AGENTS.md.orig").read_text(encoding="utf-8"), encoding="utf-8")
    shutil.rmtree(harness_dir)
    return True
